language: node_js

sudo: false
node_js:
  - "4.1"

before_install:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - npm install -g electron-prebuilt

script:
  - npm run test:browser

after_script:
  - cat henderson.js | wc -c
